import type { Hono } from 'hono'
import { evaluateSwapPolicy, parseSwapInput, SwapInputError } from './swap.js'
import { observeSwap } from './swapObservation.js'
import { signSwapObservation, signSwapPreflight, verifySwapArtifact, type SwapPreflightArtifact } from './swapEvidence.js'
export const INSPECT_SWAP_DESCRIPTION='FREE. Deterministically inspect a narrow Base USDC-to-WETH direct Uniswap V3 swap against explicit policy. No wallet action or signing.'
export const PREFLIGHT_SWAP_DESCRIPTION='Call BEFORE an agent asks its wallet to execute a narrow Base USDC-to-WETH direct Uniswap V3 swap. OCD returns a signed portable policy artifact. ALLOW is policy only, never wallet authority.'
export const OBSERVE_SWAP_DESCRIPTION='Given a signed OCD swap preflight artifact and Base transaction hash, independently inspect direct Uniswap V3 exactInputSingle calldata, ERC-20 transfers, and Base safe-head finality. OCD never executes the swap.'
export async function inspectSwap(raw:unknown){const i=parseSwapInput(raw),e=evaluateSwapPolicy(i);return{...e,action:i.action,policy:i.policy,signed_artifact:null}}
export async function preflightSwap(raw:unknown){const i=parseSwapInput(raw),e=evaluateSwapPolicy(i);return{...e,artifact:await signSwapPreflight({...e,action:i.action,policy:i.policy})}}
export async function observeSwapAction(raw:any){if(!raw||typeof raw!=='object'||typeof raw.transaction_hash!=='string'||!raw.artifact)throw new SwapInputError('body must contain artifact and transaction_hash');const v=await verifySwapArtifact(raw.artifact);if(v.state!=='VALID')throw new SwapInputError(`preflight artifact is not verifiable: ${v.code}`);const p=(raw.artifact as {data:SwapPreflightArtifact}).data;if(p.artifact_type!=='PREFLIGHT')throw new SwapInputError('artifact must be a PREFLIGHT swap artifact');return{artifact:await signSwapObservation(p,await observeSwap(raw.transaction_hash))}}
export function mountSwapRoutes(app:Hono){const response=(f:(body:unknown)=>Promise<any>)=>async(c:any)=>{try{return c.json(await f(await c.req.json()))}catch(e:any){return c.json({error:e?.message||'swap request failed'},e instanceof SwapInputError?400:502)}};app.post('/inspect/swap',response(inspectSwap));app.post('/swaps/observe',response(observeSwapAction));app.post('/verify-swap-action',async c=>{try{return c.json(await verifySwapArtifact(await c.req.json()))}catch{return c.json({state:'INVALID',code:'body-invalid',message:'body must be JSON'},400)}})}
