/** Independent, narrow direct-Uniswap-v3 exactInputSingle observation. */
import { decodeFunctionData, getAddress, parseAbi, parseEventLogs, type Hex, type Log } from 'viem'
import { evaluateBaseFinality, type FinalityEvaluation } from './finality.js'
import { getClient, isValidTransactionHash } from './settlement.js'
import { BASE_CAIP2, BASE_USDC } from './settlementNetworks.js'
import { BASE_WETH, UNISWAP_V3_SWAP_ROUTER02_BASE } from './swap.js'
const ABI=parseAbi(['event Transfer(address indexed from,address indexed to,uint256 value)','function exactInputSingle((address tokenIn,address tokenOut,uint24 fee,address recipient,uint256 amountIn,uint256 amountOutMinimum,uint160 sqrtPriceLimitX96) params) payable returns (uint256 amountOut)'])
export interface SwapTransfer { token:string; from:string; to:string; amount_atomic:string; log_index:number; transaction_hash:string; block_hash:string }
export interface SwapObservation { state:'not-found'|'reverted'|'success'|'unsupported-shape'|'rpc-unavailable'; network:typeof BASE_CAIP2; transaction_hash:string; router:string|null; payer:string|null; decoded_parameters:{input_asset:string;output_asset:string;recipient:string;max_input_atomic:string;min_output_atomic:string}|null; input_transfer:SwapTransfer|null; output_transfer:SwapTransfer|null; block_number:string|null; block_hash:string|null; finality:FinalityEvaluation|null; rpc_error:string|null }
export interface MinimalSwapClient { getTransactionReceipt:(a:{hash:Hex})=>Promise<{status:'success'|'reverted';blockNumber:bigint;blockHash:Hex;logs:Log[]}>; getTransaction:(a:{hash:Hex})=>Promise<{to:Hex|null;from:Hex;input:Hex}>; getBlock:(a:{blockTag:'safe'})=>Promise<{number:bigint;hash:Hex}> }
const absent=(hash:string,state:SwapObservation['state'],error:string|null=null):SwapObservation=>({state,network:BASE_CAIP2,transaction_hash:hash,router:null,payer:null,decoded_parameters:null,input_transfer:null,output_transfer:null,block_number:null,block_hash:null,finality:null,rpc_error:error})
export async function observeSwap(transactionHash:string,deps:{client?:MinimalSwapClient}={}):Promise<SwapObservation>{ if(!isValidTransactionHash(transactionHash))throw new Error('transaction_hash must be a 0x-prefixed 32-byte transaction hash'); let c:MinimalSwapClient; try{c=deps.client??getClient(BASE_CAIP2) as unknown as MinimalSwapClient}catch(e:any){return absent(transactionHash,'rpc-unavailable',e?.message||'Base RPC unavailable')} let receipt;let tx;try{[receipt,tx]=await Promise.all([c.getTransactionReceipt({hash:transactionHash as Hex}),c.getTransaction({hash:transactionHash as Hex})])}catch(e:any){return absent(transactionHash,e?.name==='TransactionReceiptNotFoundError'?'not-found':'rpc-unavailable',e?.message||'RPC lookup failed')} if(receipt.status!=='success')return {...absent(transactionHash,'reverted'),block_number:receipt.blockNumber.toString(),block_hash:receipt.blockHash}; if(!tx.to||tx.to.toLowerCase()!==UNISWAP_V3_SWAP_ROUTER02_BASE)return {...absent(transactionHash,'unsupported-shape'),router:tx.to?.toLowerCase()??null,payer:getAddress(tx.from)}; let args:any;try{args=decodeFunctionData({abi:ABI,data:tx.input}).args[0]}catch{return {...absent(transactionHash,'unsupported-shape'),router:UNISWAP_V3_SWAP_ROUTER02_BASE,payer:getAddress(tx.from)}} const params={input_asset:getAddress(args.tokenIn),output_asset:getAddress(args.tokenOut),recipient:getAddress(args.recipient),max_input_atomic:args.amountIn.toString(),min_output_atomic:args.amountOutMinimum.toString()}; if(params.input_asset.toLowerCase()!==BASE_USDC||params.output_asset.toLowerCase()!==BASE_WETH)return {...absent(transactionHash,'unsupported-shape'),router:UNISWAP_V3_SWAP_ROUTER02_BASE,payer:getAddress(tx.from),decoded_parameters:params}; const transfers=parseEventLogs({abi:ABI,logs:receipt.logs,eventName:'Transfer'}).map(l=>({token:l.address.toLowerCase(),from:getAddress(l.args.from),to:getAddress(l.args.to),amount_atomic:l.args.value.toString(),log_index:Number(l.logIndex),transaction_hash:l.transactionHash as string,block_hash:l.blockHash as string})); const payer=getAddress(tx.from); const ins=transfers.filter(x=>x.token===BASE_USDC&&x.from.toLowerCase()===payer.toLowerCase()); const outs=transfers.filter(x=>x.token===BASE_WETH&&x.to.toLowerCase()===params.recipient.toLowerCase()); const finality=await evaluateBaseFinality(c as any,receipt.blockNumber,receipt.blockHash); return {state:ins.length===1&&outs.length===1?'success':'unsupported-shape',network:BASE_CAIP2,transaction_hash:transactionHash,router:UNISWAP_V3_SWAP_ROUTER02_BASE,payer,decoded_parameters:params,input_transfer:ins.length===1?ins[0]:null,output_transfer:outs.length===1?outs[0]:null,block_number:receipt.blockNumber.toString(),block_hash:receipt.blockHash,finality,rpc_error:null} }
