/**
 * referenceReceipts.ts — the bundled, immutable Public Action Receipt v1
 * registry (see ../receiptStore.ts).
 *
 * Every entry here MUST be a genuinely signed envelope obtained from the
 * live HTTP API's /attest endpoint (purpose "public-action-receipt") — never
 * a fabricated or locally-signed proof. Generated by
 * scripts/generateReferenceReceipt.ts.
 */
import type { PublicActionReceiptEnvelope } from '../receipts.js'

export const REFERENCE_RECEIPTS: PublicActionReceiptEnvelope[] = [
  {
    schema: 'onchaindiligence.public-action-receipt.v1',
    receipt: {
      receipt_type: 'ACTION',
      issued_at: '2026-08-28T19:53:51.415Z',
      action: { kind: 'planned-financial-transfer', resource: 'AAPL counterparty preflight', network: 'ethereum-mainnet', asset: 'pathUSD', amount: '1.00', sender: null, recipient: '0x000000000000000000000000000000000000dEaD' },
      decision: { status: 'REQUIRE_APPROVAL', authorized: false, reasons: ['Recipient wallet was not bound to the resolved SEC filer.', 'Independent public observations do not establish a wallet-to-company identity relationship.'] },
      execution: { provider: 'OnChainDiligence Agent Evidence P1.8 reference workflow', status: 'NOT_SUBMITTED', transaction_hash: null, submitted_at: null, confirmed_at: null },
      settlement: { status: 'NOT_APPLICABLE', detail: 'No execution was submitted; no value settlement occurred.' },
      checks: [
        { id: 'recipient-wallet-not-sanctioned', result: 'PASS', summary: 'The public burn address was reported not sanctioned by the Chainalysis oracle at the recorded observation time.', evidence_digest: 'sha256:-1OOwqRghEqt0CUdq9EO-49aUlWnRBTRj1QDODO9GqA' },
        { id: 'counterparty-sec-filer-resolved', result: 'PASS', summary: 'AAPL was resolved to Apple Inc. through SEC EDGAR at the recorded observation time.', evidence_digest: 'sha256:cvd9KFwcUlJY_obJrR6OdwFY2Q3wQJSwvp_8yv1wa6U' },
        { id: 'recipient-wallet-bound-to-counterparty', result: 'FAIL', summary: 'No public evidence in this run established that the recipient wallet belongs to the resolved SEC filer.', evidence_digest: null },
      ],
      links: { agent_evidence_bundle_digest: 'sha256:b3Y51kb7-JfTCzA-MbVBHAiLdo43xlJLpAbT4eed6rw', preflight_receipt_id: null },
      limitations: ['A valid receipt proof does not prove every underlying evidence statement is objectively true.', 'Execution was not submitted.', 'No value settlement occurred.', 'Wallet and company identity bindings are not implied unless separately proven.'],
      receipt_id: 'OCD-RCP-EMG6-6KR4-PQSG-MZPQ',
      receipt_digest: 'sha256:dSBjTwS18wp-15gRHOmTW_2zUKOaXjH9pil1hJcNclY',
    },
    proof: {
      signed: true,
      schema_version: 'onchaindiligence.attestation.v2',
      issuer: 'https://api.onchaindiligence.com',
      purpose: 'public-action-receipt',
      issued_at: '2026-09-03T20:56:24.757Z',
      key_id: 'ed25519-P2jIwhCn-Af6pTz4',
      algorithm: 'ed25519',
      canonicalization: 'RFC8785',
      signature: 'URyO6GlX7T9upAaaemBbqBY55CEyslNuioEGWjyoRdH9Dm9YvVQiaxpUpK8OHLs5zwdrIldvFj177wJGwEYXAQ',
    },
  },
]
