/**
 * referenceReceipts.ts — the bundled, immutable Public Action Receipt v1
 * registry (see ../receiptStore.ts).
 *
 * Every entry here MUST be a genuinely signed envelope obtained from the
 * live HTTP API's /attest endpoint (purpose "public-action-receipt") — never
 * a fabricated or locally-signed proof. Generated by
 * scripts/generateReferenceReceipt.ts.
 */
import type { PublicActionReceiptEnvelope } from '../receipts.js'

export const REFERENCE_RECEIPTS: PublicActionReceiptEnvelope[] = []
